export type icons =
    | undefined
    | "desktop"
    | "reset"
    | "discard"
    | "info"
    | "record"
    | "continue"
    | "pause"
    | "stop"
    | "download"
    | "sun"
    | "moon"
    | "mic"
    | "camera"